### ISSUE TITLE
name change

### ISSUE THREAD

**Issue by mpenet** [mpenet/hirundo#12]
mina is also an apache project with somewhat overlapping context, sadly I missed that when I named this library. 

I could change the name to something else:

* nima (as the parent codename project) 
* hirundo 
* `<something else>`
* leave it as is, mina

**Comment by isaksky** [comment]
Hirundo is a cool name. Some other ideas:

- nima-clj: Boring, low-risk option. With this one I think the `-clj` suffix can be omitted from the namespaces, it could just be the package and project name.

**Comment by isaksky** [comment]
Another idea:

![image](https://github.com/mpenet/mina/assets/607986/1e744aab-eb17-4dc2-8243-9303acf27fe0)

So you could translate 'full moon' into some other language. Some examples:

![image](https://github.com/mpenet/mina/assets/607986/15f7d427-9ebc-4787-870b-f9f55268f05a)

**Comment by mpenet** [comment]
went with hirundo!
