### ISSUE TITLE
Adapt to the Ring websocket spec

### ISSUE THREAD

**Issue by lispyclouds** [mpenet/hirundo#13]
With the upcoming 1.11+ release of ring and the jetty adapter being based on Jetty 11, websocket support is now added too. Would it make sense for mina to use the same [spec](https://github.com/ring-clojure/ring/blob/master/SPEC-alpha.md#3-websockets) too? It has it's own but this could make it more compatible hopefully.

**Comment by mpenet** [comment]
I saw that one coming, but it's not so easy with helidon. There is no way to do this with the way helidon routing works, there's a clear separation between the various protocols. I asked on the slack of helidon devs: 

> Tomas Langer
  [6 days ago](https://helidon.slack.com/archives/C04CRGJ7ZEJ/p1697207124671969?thread_ts=1697008146.266189&cid=C04CRGJ7ZEJ)
The concept in Helidon is that there is a connection, and depending on the user request, we decide how to handle it (e.g. upgrade happens before routing is selected).
I think our current abstraction of HTTP requests would not allow this, as when you reach routing, you are handling an HTTP request, and we expect an HTTP response.
You may be able to work around it (though it would be a bit complicated, and I am not even sure this would work):
disable discovery of HTTP/1.1 upgraders
in the route, get input and output stream
manually call WsUpgrader.upgrade() (would require some code to create all the required parameters) - such as providing WsRouting in the router of the context, so the route is correctly discovered and handled using websocket
start a thread to call ServerConnection.handle(Semaphore)
join the thread
One of the problems may be what to do when that connection finishes, as you are still in HTTP routing, so whatever you would do would probably end up in an exception - though you may just call send() and ignore the exception...


There might be a way to improve a bit routing so it's not just a static table of `path` -> `listener` but that's about it with the current builds.

**Comment by lispyclouds** [comment]
Looks gnarly and seems difficult. We could stick with the different one like it is now, [rj9a](https://github.com/sunng87/ring-jetty9-adapter#websocket) definitely has its own which is unlikely change i suppose.

**Comment by mpenet** [comment]
Even doing what I mention is not possible right now, the implementation that uses a Supplier creates a WsListener instance for every connection from the one we supply for HttpUpgrade and they throws it away, we we can't save the httpprologue info (basically what we use for building the ring request), and creates another one later to handle messages/open/connect/close etc, droping all info we potentially "saved" on upgrade. 
I believe it's a bug, discussing that with helidon devs.

**Comment by mpenet** [comment]
Ref https://github.com/helidon-io/helidon/issues/8039

**Comment by mpenet** [comment]
the bug mentioned earlier is fixed upstream and now propagated to hirundo.
