### ISSUE TITLE
Cannot call `select-keys` on `request` with missing keys

### ISSUE THREAD

**Issue by julienvincent** [mpenet/hirundo#17]
Attempting to call `(select-keys request [:missing-key])` fails with:

```
java.lang.NullPointerException: Cannot invoke "clojure.lang.IMapEntry.val()" because "e" is null
```

Would love to use this lib but we do a lot of req manipulation and this means this is not a drop-in replacement for other ring compliant adapters.

Any chance this could be resolved?

**Comment by mpenet** [comment]
Hi,

Thanks for the report. That looks like a bug indeed.

I am in the middle of a pretty complicated relocation so I won’t be able to look at it before the weekend.

**Comment by mpenet** [comment]
Hi, 

0.1.29 fixes these issues. I don't really have time until next week to dig deeper so I just simplified all these bits and will revisit the "lazy map" approach for headers and request once I am back 100%.

**Comment by julienvincent** [comment]
Thanks! I actually forked and did the exact same thing (removed zmap) but wasn't sure if you would have wanted this.

I did some primitive testing and I didn't notice any performance difference, I'm not sure it's really necessary to try re-add it.

I also found some other issues with headers which I fixed in my fork - I will try clean up and upstream when I get a moment.
