### ISSUE TITLE
Simplify implementation of ring.core.protocols.StreamableResponseBody

### ISSUE THREAD

**Issue by lispyclouds** [mpenet/hirundo#19]
With the release of Ring [1.12.0](https://clojurians.slack.com/archives/C06MAR553/p1710169716434309) ring-core-protocols is [available](https://clojars.org/org.ring-clojure/ring-core-protocols) as a zero deps stand-alone lib.
This should simplify the relatively complex [implementation](https://github.com/mpenet/hirundo/blob/main/src/s_exp/hirundo/http/response.clj#L46) of the protocol here to avoid the big transitive deps.
If there is interest, I can raise a PR doing this.

**Comment by mpenet** [comment]
Oh, I missed that one. Sure, go for it. I'd happily review work on this.
