### ISSUE TITLE
production ready?

### ISSUE THREAD

**Issue by sorumehta** [mpenet/hirundo#22]
Hi, first of all, thank you for making this ring adapter for Nima. It allows me to not worry about async handling while retaining performance, which is great!
I want to use it for a project that I am building, which hopefully would go to production some day. Is hirundo production ready?

**Comment by mpenet** [comment]
Hi, 

It depends on your definition of production ready. Helidon 4.x is no longer an alpha/beta/rc, so I suppose it can be considered as such. 
This adapter is a very thin layer on top of it, while I cannot guarantee that it's not totally bug-free (who can), it's certainly very usable already in my opinion.
